paths:
  /api/deliveries/history/{agentId}/{deliveryId}:
    get:
      summary: Obtener detalle de una entrega específica
      tags:
        - Historial de Entregas
      parameters:
        - in: path
          name: agentId
          required: true
          schema:
            type: string
          description: ID del repartidor
        - in: path
          name: deliveryId
          required: true
          schema:
            type: string
          description: ID de la entrega
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Token JWT del repartidor
      responses:
        "200":
          description: Detalle de la entrega encontrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    example: "507f1f77bcf86cd799439011"
                  clientName:
                    type: string
                    example: "Juan"
                  clientLastname:
                    type: string
                    example: "Pérez"
                  clientFullName:
                    type: string
                    example: "Juan Pérez"
                  address:
                    type: string
                    example: "Av. Siempreviva 742"
                  status:
                    type: string
                    enum: [in_transit, pending, delivered, cancelled]
                    example: "delivered"
                  qrCode:
                    type: string
                    example: "QR123456"
                  packageLocation:
                    type: object
                    properties:
                      sector:
                        type: string
                        example: "A"
                      shelf:
                        type: string
                        example: "3"
                      column:
                        type: string
                        example: "2"
                  initDateTime:
                    type: string
                    format: date-time
                    example: "2024-03-15T10:00:00Z"
                  endDateTime:
                    type: string
                    format: date-time
                    example: "2024-03-15T11:30:00Z"
                  deliveryTime:
                    type: string
                    example: "1.50 hours"
        "404":
          description: Entrega no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Entrega no encontrada"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Ocurrió un error al obtener los detalles de la entrega"

  /api/delivery-details/{routeId}:
    get:
      summary: Obtener detalle de una entrega específica por ID de ruta
      tags:
        - Historial de Entregas
      parameters:
        - in: path
          name: routeId
          required: true
          schema:
            type: string
          description: ID de la ruta de entrega
      responses:
        "200":
          description: Detalle de la entrega encontrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    example: "507f1f77bcf86cd799439011"
                  clientName:
                    type: string
                    example: "Juan"
                  clientLastname:
                    type: string
                    example: "Pérez"
                  clientFullName:
                    type: string
                    example: "Juan Pérez"
                  address:
                    type: string
                    example: "Av. Siempreviva 742"
                  status:
                    type: string
                    enum: [in_transit, pending, delivered, cancelled]
                    example: "delivered"
                  qrCode:
                    type: string
                    example: "QR123456"
                  packageLocation:
                    type: object
                    properties:
                      sector:
                        type: string
                        example: "A"
                      shelf:
                        type: string
                        example: "3"
                      column:
                        type: string
                        example: "2"
                  initDateTime:
                    type: string
                    format: date-time
                    example: "2024-03-15T10:00:00Z"
                  endDateTime:
                    type: string
                    format: date-time
                    example: "2024-03-15T11:30:00Z"
                  deliveryTime:
                    type: string
                    example: "1.50 hours"
        "404":
          description: Entrega no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Ruta no encontrada"
                  routeId:
                    type: string
                    example: "507f1f77bcf86cd799439011"
        "400":
          description: Formato de ID incorrecto
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Formato de ID incorrecto"
                  message:
                    type: string
                    example: 'Cast to ObjectId failed for value "invalid-id" at path "_id"'
                  routeId:
                    type: string
                    example: "invalid-id"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Ocurrió un error al obtener los detalles de la entrega"
                  message:
                    type: string
                    example: "Error message details"

  /api/delivery-history-list:
    get:
      summary: Obtener listado de entregas realizadas
      tags:
        - Historial de Entregas
      parameters:
        - in: query
          name: deliveryId
          schema:
            type: string
          description: ID opcional del repartidor para filtrar entregas
          required: false
      responses:
        "200":
          description: Lista de entregas obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "507f1f77bcf86cd799439011"
                    state:
                      type: string
                      enum: [delivered]
                      example: "delivered"
                    end_date_time:
                      type: string
                      format: date-time
                      example: "2024-03-15T11:30:00Z"
                    client_name:
                      type: string
                      example: "Juan"
                    client_lastname:
                      type: string
                      example: "Pérez"
                    delivery_time:
                      type: string
                      example: "1.50 hours"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An error occurred while fetching the delivery history."
